[tool.ruff]
target-version = "py310"
line-length = 79

select = ["W", "E", "F", "I"]
fixable = ["W", "E", "F", "I"]
# Do not auto-fix unused variables.
unfixable = ["F841"]
ignore = []

exclude = [".tox", ".ruff_cache", ".git", "env"]
